name: Fetch new resources of the sources

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  pythonSources:
    name: Handling all the python based sources
    runs-on: ubuntu-latest
    steps:
      - name: checking out the repo
        uses: actions/checkout@v3
      
      - name: setting up python dependecies
        run: pip3 install -r requirements.txt
      
      - name: download database
        env:
          DATABASE_URL: https://media.githubusercontent.com/${{github.repository}}/db/database.db
        run: |
          if curl -I -s -f $DATABASE_URL -o /dev/null;
            then
              curl -s $database_url -o database.db
              echo "file downloaded"
            else
              echo "database doesn't exists"
          fi 
      
      - name: download log file
        run: |
          logfile_url="https://media.githubusercontent.com/${{ github.repository }}/db/resource_scrapper.log"
          if curl -I -s -f $logfile_url --output /dev/null;
            then
              curl -s $logfile_url -o resource_scrapper.log
          fi
      
      - name: checking dirs
        run: tree .
        
      - name: fetching the new resources of the sources
        run: |
          for file in scrappers/python/[a-zA-Z0-9]*.py; do
            baseFilename="$(basename $file)"
            filename="${baseFilename%.*}"
            python3 -m scrappers.python.$filename
          done
      
      - name: building json files from database
        run: python3 build_script.py
        
      - name: checking post dirs
        run: tree .
        
      - name: clearing all the source code
        run: |
          rm -rf .github/
          rm -rf scrappers/
          rm -rf utils/
          rm -rf build_script.py
          rm -rf README.md
          rm -rf requirements.txt
          rm -rf .gitignore

      - name: update the database with new resources
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Updated database of python sources"
          branch: db
          push_options: '--force'
          create_branch: true 

        # uses: EndBug/add-and-commit@v9
        # with:
        #   new_branch: db
        #   message: 'Updated database of python sources'
